os: linux
language: node_js
node_js: stable
yarn: stable
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install wine -qq
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_globs: true
  file: dist/**/*
  skip_cleanup: true
  on:
    branch: release
